---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: odoo-service
  namespace: erp-odoo
spec:
  chart:
    spec:
      version: 28.2.2
  values:
    resources:
      requests:
        memory: 1024Mi
        cpu: 512m

    replicaCount: 1
