---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: erp-source
  namespace: flux-system
spec:
  insecure: true
  interval: 1m
  provider: generic
  ref:
    tag: local
  url: oci://kind-registry:5000/erp-sync
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: erp-db-pg
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-ks
    - name: cloudnative-pg-ks
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: OCIRepository
    name: erp-source
  path: ./database/local
  prune: true
  wait: true     
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: erp-odoo
  namespace: flux-system
spec:
  dependsOn:
    - name: erp-db-pg
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: OCIRepository
    name: erp-source
  path: ./odoo/local
  prune: true
  wait: true      